### PR TITLE
Kr ducky anilist plugin 1

### PR DESCRIPTION
**Pull request by KRDucky**
## CLA

[X] I agree that by opening a pull requests I am handing over copyright ownership of my work contained in that pull request to the FileFlows project and the project owner. My contribution will become licensed under the same license as the overall project.

AniList Show and Episode lookup plugin

### CODE REVIEW

**Comment by revenz** [comment]
Not ignoring this, I just have to refactor it and make it more generic/use shared methods.

Like call it Anime TV Lookup, Anime Episode Lookup etc.

**Comment by KRDucky** [comment]
no worries. I used ChatGPT to help bang it out

**Comment by revenz** [comment]
This code doesnt actually work.

**Comment by KRDucky** [comment]
Well it was worth a try

**Pull request closed without merging**
